Hello readers! I’m back this week with another reflection on learning and knowledge, courtesy of Elizabeth Eisenstein.

---

First, let’s get the obligatory (but hopefully helpful!) bits out of the way: I’m [Chris Krycho](https://v5.chriskrycho.com) and this is my weekly newsletter—in which I publicly reflect on the things I’m learning on a wide variety of subjects: currently focused largely on theological anthropology, the history of technology, and epistemology. If someone forwarded you this email and you *like* it, you can subscribe [here](https://buttondown.email/chriskrycho). If you want to unsubscribe for any reason, you can do that [here]({{unsubscribe_url}}).

---

This week my copy of Elizabeth Eisenstein’s [<cite>The Printing Press as an Agent of Change</cite>][ee] (<i>n.b.</i>: affiliate link), and while I’m only through the introduction I’m enjoying it so far. This particular quote from the introduction stuck out to me as very much relevant to my own projects this year, and indeed to the kind of intellectual project on which I find myself in general:

> While trying to cover this unfamiliar ground I discovered (as all neophytes do) that what seemed relatively simple on first glance became increasingly complex on examination and that new areas of ignorance opened up much faster than old ones could be closed. As one might expect from a work long-in-progress, first thoughts had to be replaced by second ones, even third thoughts have had to be revised. Especially when I was writing about the preservative powers of print (a theme assigned special importance and hence repeatedly sounded in the book), I could not help wondering about the wisdom of presenting views that were still in flux in so fixed and permanent a form. I am still uncertain about this and hope that my decision to publish at this point will not be misinterpreted. I have not reached any final formulation but have merely become convinced that beyond this provisional resting point, diminishing returns will set in. (p. xii)

Eisenstein here captures something that anyone who has ever *really* studied something knows: the further along you get, the more you realize how much more there is to know. It does not matter what the field of study: there is always an (effectively) infinite amount to know, and therefore always more than we can hope to grasp fully.

This is not merely a function of modernity and the wealth of knowledge we have amassed and the specialization those depths demand. It was just as true whenever the last person who could safely be said actually to know everything that humanity collectively yet understood in any field or even in all fields. The world itself, and its history human otherwise, still beckoned: there is more you do not know, more to be learned, more to discover. This is the great joy of learning as I experience it: the combination of humbling before a universe far greater than I could ever grasp—and still more before a God who is infinitely greater than the universe which he created and sustains—with the unending delight of finding the universe—and its Creator—more wonderful and amazing than I realized before.

There is a way in which the kind of revisiting and revising Eisenstein points to could provoke frustration. If could become a reason for doubting that we ever get at the truth in a meaningful way. There is certainly a strain of late modern thought that runs this direction—I am also reading Jean-François Lyotard’s [<cite>The Postmodern Condition</cite>][tpm] (<i>n.b.</i>: another affiliate link), and suffice it to say it sounds this note in a variety of ways and for a variety of reasons—but this certainly does not seem a *necessary* response to the way the world ultimately exceeds our grasp. To the contrary, in fact.

The best analogy I can think of is climbing a mountain: sometimes, you come over a ridge thinking you’re nearly done… and realize there is but another ridge ahead of you. This can be exhausting and demoralizing. (Certainly it was at a couple points on [my run today][strava]!) At the same time, it can be exhilarating. Each little summit is a victory, and the moments where you pause to take a look at where you’ve come can be breathtaking. New vistas open up before you, with their own beauties.

In research and learning, those vistas tend to involve reevaluation of what has come before, and like Eisenstein (if to an infinitely lesser degree!) I have felt the pain of that need for revision, the challenge of deciding to commit the words to the world anyway, and the joy of doing so. Eventually, you realize that revision is a permanent state of affairs, and you just have to publish anyway—knowing that your work is incomplete and that when you read it again in a year or five, you will see mistakes, errors, things you didn’t know. That is just an inevitability when publishing—the cost of making your learning matter to others and not just yourself.



[ee]: https://click.linksynergy.com/deeplink?id=qvtf8Hp8DGA&mid=2653&murl=https%3A%2F%2Fwww.alibris.com%2FThe-Printing-Press-as-an-Agent-of-Change-Elizabeth-L-Eisenstein%2Fbook%2F5343362%3Fmatches%3D27
[tpm]: https://click.linksynergy.com/deeplink?id=qvtf8Hp8DGA&mid=2653&murl=https%3A%2F%2Fwww.alibris.com%2FThe-Postmodern-Condition-A-Report-on-Knowledge-Jean-Francois-Lyotard%2Fbook%2F5256171%3Fmatches%3D68
[strava]: https://www.strava.com/activities/3103072124