When I launched the newsletter a month ago, I promised that most of the time I’d be sending out collections of links, and *sometimes* sending out longer, more reflective pieces. In reality, it seems that even the collections of links will come with commentary. This… probably shouldn’t surprise anyone who’s followed my writing over the years. So too it goes this week; but this time I cannot claim any unifying theme other than “things I read that were interesting.”

1. <b>[How Tech Utopia Fostered Tyranny][1] (Jon Askonas, <cite>The New Atlantis</cite>, Winter 2019):</b> The last few years have seen a flurry of high-profile cases of mobs, dictators, and, yes, election interference empowered by digital technologies and social media in particular. It is tempting for Silicon Valley to treat these as incidental side effects of things that are themselves inherently good—what Ben Thompson describes as [the Polyannish Assumption][thompson]. Askonas will have none of that:

    > Much of the politics of Silicon Valley is explained by this Promethean exchange: gifts of enlightenment and ease in exchange for some measure of awe, gratitude, and deference to the technocratic elite that manufactures them. Algorithmic utopianism is at once optimistic about human motives and desires and paternalistic about humans’ cognitive ability to achieve their stated preferences in a maximally rational way. Humans, in other words, are mostly good and well-intentioned but dumb and ignorant. We rely on poor intuitions and bad heuristics, but we can overcome them through tech-supplied information and cognitive adjustment. Silicon Valley wants to debug humanity, one default choice at a time.

    The net of this is that many of the tech companies aim to *control* you: it benefits them financially *and* meshes with their ideology. It is no surprise, then, that all sorts of tyrannies—whether of dictators or of mobs—would find these opaque and paternalistic tools useful and empowering.

    (Note that Jon is a friend of mine… but, hilariously, I didn’t realize he wrote this till I opened the link to share it with you today. Nice work, Jon!)

2. <b>[Google.gov][2] (Adam J. White, <cite>The New Atlantis</cite>, Spring 2018):</b> A complement to the previous piece, in many ways, looking at how Obama’s paternalism and Google’s were complementary forces throughout his presidency… even if Obama has since grown more skeptical of the powers of technology. It’s amazing what losing an election to a demagogue will do for your take on the same technologies that were such a useful part of your own campaigns! My bemusement aside, the piece is a really interesting look at how Google’s view of itself and its goals both have *and have not* changed over time.

    What is perhaps most interesting to me in this piece is the quiet implication of the *dangers* of a world in which Google (or Facebook, or…) were to do what so many of us have wanted and filtered out the nonsense—the [perverse][yt] or the [dangerous][pinterest]. (A world, I note, which already exists to some degree!) The challenge, and the reason that they have been so leery of making these moves is that these companies are increasingly *functioning* as public forums, and as such making those moves amounts to [a kind of restriction on free speech][free speech]. (Before you grump at me, read that link! I covered the objections, I promise!) But that suggests to me not that those kinds of restrictions aren’t warranted, but that something else, much bigger, needs to change. Perhaps, just perhaps, having all of our communication flow through a handful of megacorporations *isn’t* a good idea after all? 

3. <b>[Why Racism is Material Heresy and Ought to be Formal Heresy][3] (Bradly Mason, February 2018):</b> a reflection on how and why racism is not merely *bad* but in fact *formally* heretical—that is, contrary to the very fundamentals of the Christian faith. This takes a pretty deep dive on the early ecumenical creeds, which did the hard work of hashing out the Christian doctrine of God and of the nature of Jesus Christ, the God-Man. And Mason is right: racism *does* contradict those essentials of the faith.

    I’ve been in camp “racism is un-Christian and sub-Christian” for a long time. Mason’s argument here goes further: it says that affirming racism means you have failed understand the *fundamentals* (and not merely the implications) of the good news Christianity proclaims. Particularly given the resurgence of a kind of pseudo-Christian white nationalism, this is an important and timely argument. As for its implications on a great many white Christian heroes in history, well… we should judge them as harshly as they deserve on this point, even while being humble about the fact that we do not realize where future generations are apt to find *us* wanting.

4. <b>[Randomized trial on gender in Overwatch][4] (Dan Luu, February 2019):</b> Dan Luu used a feminine-sounding name while playing Overwatch and observed how it differed from the experience of playing with a masculine-sounding name. This is not your average <i>here are some assorted observations</i> kind of report. Luu notes possibly confounding factors, and does a bunch of work on this statistically and notes all the limitations of this limited sort of study. (The amount of effort it would take to do a study with statistical significance in this environment is staggering.) The net of that work is a properly-caveated and still *very* interesting report on the differences in how men and women are treated in a game like this.

5. <b>[Can History be Open Source? Wikipedia and the Future of the Past][5] (Roy Rosenzweig, June 2006):</b> it is fascinating to see this historian’s thoughts on Wikipedia back when Wikipedia was only five years old, some 12½ years ago. Much of what he wrote then holds today; both the great strengths and the deep failings of Wikipedia are structural and therefore endemic. Rosenzweig’s take is even-handed and careful: it calls out the things Wikipedia does *well* and encourages professional historians to take it more seriously, even as it notes the inherent limitations of a publicly-written and -edited encyclopedia.

[1]: https://www.thenewatlantis.com/publications/how-tech-utopia-fostered-tyranny
[thompson]: https://stratechery.com/2017/the-pollyannish-assumption/
[2]: https://www.thenewatlantis.com/publications/googlegov
[yt]: https://www.wired.co.uk/article/youtube-pedophile-videos-advertising
[pinterest]: https://www.theguardian.com/technology/2019/feb/20/pinterest-anti-vaxx-propaganda-search-facebook
[free speech]: https://www.chriskrycho.com/2018/free-speech.html
[3]: https://alsoacarpenter.com/2018/02/07/racism-material-heresy-formal-heresy-outline-1/
[4]: http://danluu.com/overwatch-gender/
[5]: https://rrchnm.org/essay/can-history-be-open-source-wikipedia-and-the-future-of-the-past/