I have been thinking a lot over the last month about Alan Jacobs’ comments [here][aj] on “stock” and “flow” in newsletters:

> It strikes me that there are two basic kinds of newsletter.
>
> The first — and by far the most common — is **a device for flow management**. You know, the “cool stories I read this week” kind of thing. And those can be useful and illuminating! — I mean no disrespect at all — I subscribe to several such newsletters. But I want to make the other kind.
> 
> That other kind is an **aid to stock replenishment**. Interestingly enough, I think both [Robin’s newsletter](https://www.robinsloan.com/) and [Austin’s](https://austinkleon.com/newsletter/) are of this type: they focus on matters of evergreen rather than topical interest. And that’s my aspiration too. I typically don’t want to link to whatever people have been talking about recently, not because I’m hostile to current events, but because many other newsletters already provide that. Basically, and to put the point in what might be an overly elevated way, I want to point my readers towards things that are true or good or beautiful. And surely we’re not oversupplied with any of those. (I also do “funny.” Or try to, sometimes.)

Jacobs’ goal with his newsletter is the same as mine here. I hope that’s clear with the kinds of materials I share: few of the articles are particularly timely; many of them are *long* essays; all of them are more interested in the deep things of life and the ways we live life well (Aristotle’s notion of <i>eudaimonia</i>) than how we simply get ahead with The Next Big Thing.

With that in mind, the thing I have been thinking about most over the last few days is the [“slow web”][slow web]—a phrase I had actually never encountered before this week, but one that rings very true to me. Not for nothing did my cohost and I win our podcast on technology, religion, ethics, and art “Winning Slowly”: that idea of <i>slowness</i> is one that is too absent from most of our considerations of the world we encounter. The *now*, the *immediate future*: these are the things that consume us—whether in the form of constantly refreshing our social feeds (to see, especially, if people have responded positively to what we just posted), or in the form of quarterly-increase-in-profits-obsessed Wall Street traders. This is doubly foolish: not only in its short-sightedness but in its lack of of grasp on the *past*.

I have been reading St. Athanasius’ <cite>On the Incarnation</cite> these past few weeks—I *want* to read it every year around the time of [Annunciation], as it is one of those works that rewards both deep reading and regular rereading. Many English publications of Athanasius’ argument for much of the last century have included a preface by C.S. Lewis: a short and sweet argument that we should all spend more time reading old things (and less reading people’s current comments on them):

> Every age has its own outlook. It is specially good at seeing certain truths and specially liable to make certain mistakes. We all, therefore, need the books that will correct the characteristic mistakes of our own period. And that means the old books. All contemporary writers share to some extent the contemporary outlook—even those, like myself, who seem most opposed to it. Nothing strikes me more when I read the controversies of past ages than the fat that both sides were usually assuming without question a good deal which we should now absolutely deny. They thought that they were as completely opposed as two sides could be, but in fact they were all the time secretly united—united with each other and against earlier and later ages—by a great mass of common assumptions. We may be sure that the characteristic blindness of the twentieth century—the blindness about which posterity will ask, “But how could they have thought that?” —lies where we have never suspected it, and concerns something about which there is untroubled agreement between Hitler and President Roosevelt or between Mr. H.G. wells and Karl Barth. None of us can fully escape this blindness, but we shall certainly increase it, and weaken our guard against it, if we read only modern books. Where they are true they will give us truths which we half knew already. Where they are false they will aggravate the error with which we are already dangerously ill. The only palliative is to keep the clean sea breeze of the centuries blowing through our minds, and this can be done only by reading old books. Not, of course, that there is any magic about the past. People were no cleverer then than they are now; they made as many mistakes as we. But not the same mistakes. They will not flatter us in the errors we are already committing; and their own errors, being now open and palpable, will not endanger us. Two heads are better than one, not because either is infallible, but because they are unlikely to go wrong in the same direction. To be sure, the books of the future would be just as good a corrective as the books of the past, but unfortunately we cannot get at them.

(To this I would add that we also would do well to read things from people of other *cultures* than our own. Although a woman in India and I do share many things in common due to our shared age, we have many differences as well, which may prove similarly helpful as contrasts as do temporal differences.)

When Jack Cheng wrote “The Slow Web” back in 2012, he was already then contrasting it with the Fast Web:

> What is the Fast Web? It’s the out of control web. The oh my god there’s so much stuff and I can’t possibly keep up web. It’s the spend two dozen times a day checking web. The in one end out the other web. The web designed to appeal to the basest of our intellectual palettes, the salt, sugar and fat of online content web. It’s the scale hard and fast web. The create a destination for billions of people web. The you have two hundred twenty six new updates web. Keep up or be lost. Click me. Like me. Tweet me. Share me. The Fast Web demands that you do things and do them now. The Fast Web is a cruel wonderland of shiny shiny things.

He added this preface in 2016, with what seems to me to be an appropriate degree of regret for the optimism the post expresses for “solutions” in terms of user experiences:

> I wrote this essay (blog post, really) years ago as a way of articulating how my most-frequented websites and apps were making me feel. A number of the services listed below as examples of “Slow Web” are now defunct, and the “Fast Web” seems today to be even faster, more frenetic, more addictive. My thinking has also evolved greatly since writing this; the short version is that I no longer believe that anything this complex and systemic can be solved by a set of user-experience practices alone. (I don’t think I really believed that in the first place, to be frank.)

The key phrases there, I think, are “anything this complex and systemic.” He’s right to see it in those terms, and he’s right that mere user-experience practices can solve these sorts of problems. The fundamental challenge, it seems to me, is that our age’s default outlook is irretrievably *technocratic*. Cheng was reaching in 2012 for a way, but had recognized by 2016 that his earlier reaching for better outcomes was insufficient to the task. The majority of the writing I see in the mainstream tech-critical context—especially coming out of Silicon Valley, including things like the Center for Humane Technology—falls prey (so far as I can see with my own limited vantage point!) to exactly the kind of thing Lewis was getting at most of a century ago.

Or, as I [put it][poem] a few years ago:

<blockquote><p style="white-space: pre;">struggle as i may
i cannot escape my
modernity
for even the attempt
is but another symptom</p></blockquote>

The trend, in other words, is to attempt to address problems created by an overemphasis on *tools* and *techniques* with… more tools and techniques. At the core of our take in [Winning Slowly Season 6: Rejecting the Inevitable Future][ws-s6] was the thesis that the only right response to some technologies (and to some whole ways of life grounded in technologies!) is to *reject* them. We never fully got where I hoped to in that season, but we made a good start. And—at least for my part—our attempt to start building a hopeful kind of tech criticism in [Season 7][ws-s7] *entails* the thing we continually gestured at in Season 6. There is no *hopeful* future relationship between humans and our tools without a rejection of technocracy—without recognizing that the best thing we can do with our tools, quite often, is *set them down*.

It is hard to see that when we are immersed in the rhetoric of our own age, though. We end up with solutions that look just like the problems they set out to solve—and which, often as not, tend as a result to reinforce those problems. These kinds of things go much deeper than which apps we use or which devices we do or do not use.

That is not to say we should scorn the work done on that level. That work is necessary: we have to do not with the world we wish we had, but with the world that is. Sometimes we can help shift things at a macro scale, but we also must live as well as we may in the meantime. Put in very practical terms: our economic system’s dependence on credit scores (which no one opts into, and which have deeply pernicious effects throughout our whole economy!) is wicked. We must take a serious step back and reevaluate the whole chain of thinking that led us to it. We must not merely try to come up with a *more humane* way of solving that problem. We must ask whether the “problem” being solved with credit scores is in fact a problem itself, or if it is instead a symptom of deeply flawed structures behind it. But! *Whatever* we conclude, changing it will likely be a matter of decades of work. We must *also*, therefore, help people navigate that wicked system in the meantime.

The same kinds of thinking should animate our approach to this technocracy in which we find ourselves. We need to dig under and find the rot in the foundations, and think about how we might retrieve the good parts of the magnificent, terrible building we have constructed over the last centuries, and begin imagine our way (however haltingly) toward something genuinely *other*. But! *Whatever* we come up with, these kinds of changes are likely to be decades or centuries in their fruit-bearing. We must *also*, therefore, help people chose more wisely in the interim: to choose Slow Web technologies where we can, and to guard our time and our habits carefully, and to think about the kinds of technologies we *do* build and how they will affect others. Even more importantly, to choose what we might call *No Web* approaches at times. They will help us as we do that larger, harder task of walking slowly out of technocracy into something else, perhaps something genuinely better.

[aj]: https://blog.ayjay.org/stock-and-flow-in-newsletters/
[slow web]: https://jackcheng.com/the-slow-web/
[Annunciation]: https://en.m.wikipedia.org/wiki/Annunciation
[poem]: https://www.chriskrycho.com/2016/escape-modernity.html
[ws-s6]: https://winningslowly.org/season-6.html
[ws-s7]: https://winningslowly.org/season-7.html