This week, I spent a great deal of my “free” time working on something new. I’ll have more to say on it soon—including, next week, a link to what will at least initially be a *very* occasional update email. If you’ve been paying attention to my blog for a long enough time, the project won’t surprise you. But it’s also going to be a *very* long burn.

The net of that is that I didn’t spend a *lot* of time reading this week… and when I *was* reading, it was going back and rereading <cite>Leviathan Wakes</cite>, the first book in <cite>The Expanse</cite>, one of my favorite pieces of modern sci-fi/space opera. I commend it to you.

But the very fact that I didn’t have something *new* to send to you got me thinking: why *does* it need to be something new? I have read, and sent to [Pinboard](https://pinboard.in/), hundreds of articles over the last few years. Many of them deserve a close rereading: that is precisely the reason I sent them there. (And if Pinboard itself is [not quite satisfying my needs](https://www.chriskrycho.com/2018/continuing-to-reflect-on-my-internet-presence.html), well… remember the aforementioned project? Keep your ears open.)

So, a few articles I read *last year*, but which I think are worth your time:

1. [<b>The Case for the Wage Subsidy</b>](https://www.nationalreview.com/2018/11/case-for-wage-subsidy-government-spending-book-excerpt/) – Oren Cass, a generally conservative/free market type… argues that we should implement something that sounds an awful lot like a “universal basic income.” This idea has been coming up a lot in the last few years, as people are increasingly look for ways to tackle two big problems: the massive shifts in the labor market that have been happening and seem set to accelerate with increased automation, and the fairly sharp increase in disparity between ordinary workers and the top earners in the country. My own take on <abbr>UBI</abbr> and things like it is basically “I don’t know enough to have a well-formed opinion yet,” but seeing this coming from the *other* end of the political spectrum from where most <abbr>UBI</abbr> takes have come from certainly increased the credence I’m likely to give serious proposals in the area in the future.

2. [<b>Futures for Public Theology</b>](https://politicaltheology.com/a-response-to-reconsidering-public-theology/) – Charles Mathewes and Paul Dafydd Jones. This piece is one I keep coming back to; although I have minor points of disagreement here and there, it is as close to a charter for how I think about my own public persona and also the work [Stephen](https://stephencarradini.com) and I do on [Winning Slowly](https://winningslowly.org) as I’ve ever found. I’m going to excerpt a good little section of it here, but I really do encourage you to give the whole thing a read—this is what I’m aiming for here, even if I rarely manage to rise to anything like this level:

    > …we can say that “public theology” designates any attempt to use some particular religious perspective to interpret and make judgments about a common political or cultural situation, and simultaneously to communicate that interpretation and those judgments to an audience that reaches beyond one’s own religious community. It uses the symbols, categories, themes and narratives that are ingredient to and distinctive of a discrete perspective. It does so in the hope that it might elucidate our common situation for a community composed of people with a diversity of views, and also elucidates for those same people why and how one member of some religious tradition (or traditions) understands that situation as she or he does. This is theological reflection done in public that is also for the public. Three dimensions to this are relevant here.
    > 
    > First, public theology is therefore done “in” the public in a sense that should be quite clear. Public theologians do theological reflection not to convince others of the rightness of their commitments; they do it, rather, to explain how those commitments inform their interpretation of a matter of common concern. This amounts to a curiously “sideways-on” form of theological reflection: public theologians are self-conscious reporters of their views, rather than simply professors of them. For the audience, part of the value of public theology is therefore that it explains the theological commitments of their neighbors in ways that that audience would not otherwise understand.
    > 
    > Second, public theologians are not simply speaking as a way of explaining themselves to their public audience; more immediately, they are also trying to illuminate the topic at hand. Hence there is a very clear sense in which it is done “for” the public. Public theology directly takes as its object of attention some public concern that is widely shared, and attempts to illuminate that public concern; but it does so in the dual awareness that (a) many people do not share the public theologian’s particular religious convictions, and yet that (b) those very convictions may illuminate something about the concern that others, who do not share those convictions, may not clearly perceive. So while the “public theology” is not meant as any kind of altar-call for an individuals’ religious or metaphysical convictions, it is nonetheless a public articulation of an observation, intended as a genuine insight, that seems to the speaker to emerge from her or his particular commitments. There is some indeterminate, or at least unspecified, distance between one’s theology and the public contributions which it is being marshalled to make; and yet there is some relation between the two as well.
    > 
    > Third, public theology is also “for” the public in another, indirect sense. It models behavior. It attempts for all of us, whether religiously committed or not, to offer one example of how a reasonably self-conscious, self-critical, non-defensive individual and/or community might talk about matters of serious concern—how such a model citizen, idiosyncratically individual, inescapably particular, might, as it were, see things. In doing this, it hopes to have, as it were, knock-on effects. Perhaps an audience that hears such an attempt will be provoked to reflect, not only to think freshly about the issue at hand, and not only to see their fellow citizen and their citizens’ convictions in a new light; perhaps they will also be provoked to think more seriously about how all of our particular views are informing our assessments of and judgments about matters of common concern. And perhaps, just perhaps, the audience will be provoked to make a similarly dialogical articulation of their convictions in public.
    > 
    > When done well, public theology proceeds conversationally, with no expectation that readers or hearers will be converted to the public theologian’s overall point of view, but only with the hope that each of our views will be recognized to be coherent and worthy of consideration. Attempting to do public theology, that is to say, is a way of saying, “here’s how I see it, and I hope my remarks aid your understanding of the issue and help you better understand where I’m coming from.” This is no trivial matter. Our deepest commitments are better off being visible and legible to the world, for not to know about those commitments is not to know something civically important about us. In any pluralistic setting, fellow citizens, or fellow-members of some public, should apprehend not only one another’s conclusions, but also one another’s deliberations.

Thanks for reading! I look forward to having a link to this fun new project in *next* week’s email!